subscribers:

  camera_reading_1:
    topic: /camera1/color/image_raw #/camera/rgb/image_raw
    queue_size: 1
  camera_reading_2:
    topic: /camera2/color/image_raw #/camera/rgb/image_raw
    queue_size: 1
  camera_depth_reading_1:
    topic: /camera1/depth/image_rect_raw 
    queue_size: 1
  camera_depth_reading_2:
    topic: /camera2/depth/image_rect_raw 
    queue_size: 1


actions:

  camera_reading:
    name: /darknet_ros/check_for_objects

publishers:

  object_detector_1:
    topic: /darknet_ros/found_object_1
    queue_size: 1
    latch: false

  object_detector_2:
    topic: /darknet_ros/found_object_2
    queue_size: 1
    latch: false

  bounding_boxes_1:
    topic: /darknet_ros/bounding_boxes_1
    queue_size: 1
    latch: false

  bounding_boxes_2:
    topic: /darknet_ros/bounding_boxes_2
    queue_size: 1
    latch: false

  detection_image_1:
    topic: /darknet_ros/detection_image_1
    queue_size: 1
    latch: true

  detection_image_2:
    topic: /darknet_ros/detection_image_2
    queue_size: 1
    latch: true

  CorBBox_depth_image:
    topic: CorBBox_depth_image
    queue_size: 1
    latch: true


image_view:

  enable_opencv: true
  wait_key_delay: 1
  enable_console_output: true

camera_num: 2
